blog/urls.py
from django.urls import path
from .import views

app_name='blog'

urlpatterns=[
path('',views.index,name='index'),
path('posts/<slug:post_slug>/',views.post_content,name='post_content'),
path('categories/<slug:category_slug>/',views.category_archive,name='category_archive'),
path('<slug:post_slug>/share-this-post/',views.share_post,name='share_post')
]

project_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
]
if settings.DEBUG:
	urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

DEFAULT_CATEGORY =1 

class ActiveManager(models.Manager):
	def get_queryset(self):
		return super(ActiveManager,self).get_queryset().filter(active=True)


class Category(models.Model):
	name=models.CharField(max_length=100)
	slug=models.SlugField(max_length=100)

	class Meta:
		ordering=('name',)
		verbose_name='Category'
		verbose_name_plural='Categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('blog:category_archive',args=[self.slug])

class Post(models.Model):
	STATUS_CHOICES= (('draft','Draft'),('published','Published'),)
	title=models.CharField(max_length=200)
	slug=models.SlugField(max_length=200)
	author=models.ForeignKey(User,on_delete=models.PROTECT,default='sushant')
	category=models.ForeignKey(Category,on_delete=models.PROTECT,related_name='posts',default=DEFAULT_CATEGORY)
	featured_image= models.ImageField(upload_to='post_featured_images/')
	status=models.CharField(max_length=50,choices=STATUS_CHOICES,default='draft')
	content=models.TextField()
	created=models.DateTimeField(auto_now_add=True)
	published=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)


	class Meta:
		verbose_name='Post'
		verbose_name_plural='Posts'
		ordering=('-created',)
		
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_content',args=[self.slug])

class Comment(models.Model):
	post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
	name=models.CharField(max_length=200)
	email=models.EmailField()
	body=models.TextField()
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	active=models.BooleanField(default=True)
	objects = models.Manager() # the default manager
	ActiveComments = ActiveManager() # custom manager that retrieves active comments 

	class Meta:
		verbose_name='comment'
		verbose_name_plural='comments'

	def __str__(self):
		return 'comment on {}  by {}'.format(self.post,self.name)

blog/forms.py
from django import forms
from .models import Comment

class SharePostForm(forms.Form):
	name=forms.CharField()
	email=forms.EmailField()
	to=forms.EmailField()
	comment= forms.CharField(widget=forms.Textarea(attrs={'rows':'3'}))

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields= ('name','email','body')
		widgets={
		 'body':forms.Textarea(attrs={'rows':'3','cols':'60'})
		}

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Category
from .forms import SharePostForm,CommentForm
from django.core.mail import send_mail
from django.contrib import messages


def index(request):
	posts=Post.objects.filter(status='published')
	return render(request,'blog/index.html',{'posts':posts})

def post_content(request,post_slug):
    post= Post.objects.get(slug=post_slug)
    
    new_comment=None
    
    #get all comments that are currently active to show in the post, this queryset is not evaluated yet, it will be 
    # evaluated in the template during iteration. 
    comments= post.comments.filter(active=True)

    

    #see if there are any comments already 
    comment_exists = post.comments.filter(active=True).exists()

    if request.method=='POST':
    	comment_form= CommentForm(request.POST)
    	if comment_form.is_valid():
    		# saving a ModelForm creates an object of the corresponding model. In this case, we need to create a comment
    		# object but we haven't assigned it a post yet, so we just temporarily save it in memory(not in database)
    		# commit=False does exactly this job. And later we save it in the database after assigning post. 
    		new_comment= comment_form.save(commit=False)
    		new_comment.post=post
    		new_comment.save()
    		messages.info(request,'Comment Posted Successfully',extra_tags='comment_posted')
    		# incase of successful submission you should always use redirect rather than render because of the 
    		# "resubmission if refreshed" problem  and it may have other benefits too, yet to explore ! 
    		return redirect(post)
    	else:
    		messages.error(request,'Comment details are invalid. Probably email!', extra_tags='invalid_comment')
    		
    else:
    	comment_form=CommentForm()
    return render(request,'blog/post_content.html',{'post':post,'comments':comments,'comment_form':comment_form,'comment_exists':comment_exists})
	

def category_archive(request,category_slug):
	category=Category.objects.get(slug=category_slug)
	posts= category.posts.all()
	return render(request,'blog/category_archive.html',{'category':category,'posts':posts})

def share_post(request,post_slug):
	post=get_object_or_404(Post,slug=post_slug)
	
	sent=False
	if request.method=='POST':
		form=SharePostForm(request.POST)
		if form.is_valid():
			cd=form.cleaned_data
			post_url= request.build_absolute_uri(post.get_absolute_url())
			subject='{} recommends you reading {}'.format(cd['name'],post.title)
			message= "{}({}) suggests you to read this: {} \n at {} \n His comments: \n {} ".format(cd['name'],cd['email'], post.title,post_url,cd['comment'])
			receiver=cd['to']
			send_mail(subject,message,'code.breakit@gmail.com',[receiver])
			sent=True
			share_success_message= " Post sucessfully shared with {}".format(receiver)
			messages.info(request,share_success_message,extra_tags='post_shared')
			return redirect(post)

	else:
		form=SharePostForm()
	return render(request,'blog/share_post.html',{'post':post,'form':form,'sent':sent})

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/mainstylesheet.css'%}">
</head>
<body>
{% load custom_tags %}
	<nav class="navbar navbar-light navbar-expand-lg top-navbar">
		<div class="navbar-brand"><a href="{% url 'blog:index' %}">My Blog</a></div>
		<button class="navbar-toggler" data-toggle="collapse" data-target="#collapsiblemenu">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse" id="collapsiblemenu">
			<ul class="navbar-nav" >
				{% get_categories as categories %}
				{% for category in categories %}
				<li class="nav-item"><a href="{{ category.get_absolute_url }}" class="nav-link">{{category.name}}</a></li>
				{% endfor %}
			</ul>
		</div>
		
	</nav>

	<div class="container-fluid">
		{% block jumbotron%}
		{% endblock %}
	</div>

	<div class="container-fluid py-3">
		<div class="row">
			<div class="col-sm-9">
				{% block content %}
				{% endblock content %}
			</div>
			<div class="col-sm-3 sidebar bg-light">
				<h5 class="sidebar-header text-center">Recently Posted</h5>
				<div class="col-sm-12">
					{% recent_posts as recent_posts %}
					{% for post in recent_posts %}
			 			<p><a href="{{post.get_absolute_url}}">{{post.title|cap_initials}}</a></p>
					{% endfor %}
				</div>
				<h5 class="sidebar-header text-center">Recent Comments</h5>
				<div class="col-sm-12">
					{% recent_comments as recent_comments %}
					{% for comment in recent_comments %}
			 			<p><a href="{{comment.post.get_absolute_url}}">{{comment.body}} in <em>{{comment.post.title|cap_initials}}</em> - <small>{{comment.name|capfirst}}</small></a></p>
					{% endfor %}
				</div>
				<h5 class="sidebar-header text-center">All Categories</h5>
				<div class="col-sm-12">
					{% get_all_categories as categories %}
					{% for category in categories %}
					  
					  {% with category.posts.all.count as total_no_posts %}
					  		<p><a href="{{category.get_absolute_url}}">{{category.name}}({{total_no_posts}})</a></p>
					  {% endwith %}
					{% endfor %}
				</div>
			</div>
		</div>
		
	</div>



<div class="footer text-center">
	<p class="my-0">All rights belong to Sushant ! </p>
</div>

</body>
</html>

blog/templates/blog/category_archive.html
{%extends "base.html"%}
{%block title%} {{category.name}}{% endblock %}
{% block content %}
<div class="container-fluid">  
<div class="row">
			{% for post in posts %}
				<div class="col-sm-4">
					<div class="card">
						<img src="{{post.featured_image.url}}" width="300px" height="300px" class="justify-content-center" href="{% url 'blog:post_content' post.slug %}"/>
						<h5 class="card-title"><a href="{% url 'blog:post_content' post.slug %}">{{post.title|capfirst}}</a></h5>
						<p class="card-text">{{post.author|capfirst}}</p>
						<p class="card-text">{{post.created|date:"d M Y,D"}}</p>
					</div>
				</div>
			{% endfor %}
</div>
</div>

{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
   Welcome To My Blog ! 
{% endblock %}
{% load custom_tags %}
{% block jumbotron %}
<div class="jumbotron text-center">
	<h3>Welcome To My Blog ! </h3>
</div>
{% endblock %}

{% block content %}
  <div class="row">
  	{% for post in posts %}
				<div class="col-sm-4">
					<div class="card">
						<img src="{{post.featured_image.url}}" width="300px" height="300px" class="justify-content-center" href="{{ post.get_absolute_url }}"/>
						<h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{post.title|allcaps}}</a></h5>
						<p class="card-text">{{post.author|capfirst}}</p>
						<p class="card-text">{{post.created|date:"d M Y,D"}}</p>
					</div>
				</div>
			{% endfor %}
			
  </div>
			
{% endblock %}

blog/templates/blog/post_content.html
{% extends "base.html" %}
{% block title%} {{post.title}}{% endblock %}
{% block content %}
{% load custom_tags %}

{% if messages %}

    {% for message in messages %}

       {% if "invalid_comment" in message.tags %}
       	<p class="alert alert-warning">{{message}}</p>
       {% endif %}

       {% if "comment_posted" in message.tags %}
       	<p class="alert alert-success">{{message}}</p>
       {% endif %}

       {% if "post_shared" in message.tags %}
        <p class="alert alert-success">{{message}}</p>
       {% endif %}

    {% endfor %}

{% endif %}

<div class="container text-justify py-3">
	<h3 class="py-3">{{post.title|allcaps}}</h3>
	<img src="{{post.featured_image.url}}" width="800px" class="pb-4">
	<p style="text-indent: 50px;">{{post.content}}</p>
</div>

<div class="comment-section">
	
	{% if comment_exists %}
		{% with comments.count as total_no_comments %}
		<strong style="text-decoration: underline;">{{total_no_comments}} Comments:</strong> 
		{% endwith %}
		
		{% for comment in comments %}
	  	<p>{{comment.body}} <span class="small px-2">- by {{comment.name|capfirst}} on {{comment.created}}</span></p>
		{% endfor %}
	{% else %}
	<strong> There Are No Comments Yet !</strong>
	{% endif %}
		
 </div>


<button class="btn btn-primary mb-3" data-toggle='collapse' data-target="#comment_form">Leave a reply!</button>

<form class="container-fluid comment-form-section collapse" id="comment_form" method="POST" action=".">

	<div class="comment_form_name form-group">
		<strong>{{comment_form.name.label}}:</strong>
		{{comment_form.name}}
	</div>
	<div class="comment_form_email form-group">
		<strong>{{comment_form.email.label}}:</strong>
		{{comment_form.email}}
	</div>
	<div class="comment_form_body form-group">
		<strong>{{comment_form.body.label}}:</strong>
		{{comment_form.body}}
	</div>
	<input type="submit" name="submit" value="Post Comment" class="m-3">
	{% csrf_token %}
</form>

<div class="share-post">
	<p><a href="{% url 'blog:share_post' post.slug %}" class="btn btn-primary">Share This Post</a></p>
</div>
{% endblock %}

blog/templates/blog/share_post.html
{% extends "base.html" %}
{% block title %} Share Post {% endblock %}
{% block content %}
<h4>Share <strong>{{post.title}}</strong> through email </h4>
{% if sent %}
<h4>Email has been sent successfully </h4>
<p>	"{{post.title}}" has been successfully shared with {{form.cleaned_data.to}}</p>
{% else %}
 <form action="." method='post' class="form">
 	<div class="form-group">
 		<strong>{{form.name.label}}:</strong><br>
 		{{form.name}}
 		
 	</div>
 	<div class="form-group">
 		<strong>{{form.email.label}}:</strong><br>
 		{{form.email}}
 		
 	</div>
 	<div class="form-group">
 		<strong>{{form.to.label}}:</strong><br>
 		{{form.to}}
 		
 	</div>
 	<div class="form-group">
 		<strong>{{form.comment.label}}:</strong><br>
 		{{form.comment}}
 		
 	</div>

 	<!--{{form.as_p}}-->
 	{% csrf_token %}
 	<input type="submit" name="submit" value="Send email !" class="btn btn-primary"> 
 </form>
{% endif %}
{% endblock %}